---
AllCops:
  DisabledByDefault: true
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  Exclude:
  - tmp/**/*
  - vendor/**/*
  - examples/**/*
  - pkg/**/*
  - Rakefile
Layout/SpaceAfterColon:
  Enabled: true
Layout/SpaceAroundKeyword:
  Enabled: true
Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: no_space
  Enabled: true
Layout/SpaceBeforeFirstArg:
  Enabled: true
Layout/SpaceInsideParens:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true
Lint/Debugger:
  Enabled: true
Naming/MethodName:
  Enabled: true
  EnforcedStyle: snake_case
  Exclude:
  - test/**/**
Naming/VariableName:
  Enabled: true
Style/MethodDefParentheses:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
Metrics/ParameterLists:
  Max: 7
Layout/AccessModifierIndentation:
  EnforcedStyle: indent
Style/WhileUntilModifier:
  Enabled: true
Style/TernaryParentheses:
  Enabled: true
Bundler/GemComment:
  IgnoredGems: false
Layout/IndentationStyle:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: true
